### ISSUE TITLE
Update get-started/wallet

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#105]
**Estimated time:** 2h

---------------

**Why:**
This document is outdated.

**What:**
Should be updated with mainnet informations instead of testnet and the new version of metamask (who let you for ex set the name, chainid, etc.)

**Comment by etienne-napoleone** [comment]
Assigned to: @DuqueKarl 
Reviewed by: @etienne-napoleone

**Comment by phamvancam2104** [comment]
closed in #110
