### ISSUE TITLE
Article on TomoChain accounts

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#106]
**Estimated time:** 3h

---------------

**Why:** 
Investors seems to have little understanding about how accounts works.

**What:**
An article explaining how accounts live on the blockchain, how tools like metamask, mew, cold wallets etc, interact with them. What are addresses, privates keys, public keys, etc.

One of the goal is to educate them about their wallet. We've seen a lot of people asking (about the swap): "Is it ok if I have my coins on MetaMask? But there's actually no value stored in MetaMask. 

The only important thing for the swap is if you own the account (know the private key) or not. General awareness of how the blockchain accounts works might help them regarding this.

**Comment by etienne-napoleone** [comment]
Assigned to: @bluebottleco 
Reviewed by: @etienne-napoleone

**Comment by bluebottleco** [comment]
Please find below the draft. 

A few notes:
- I can add more about explaining a BlockChain account if you think it’s necessary but I kept it short because I think most people likely understand this given they’re using BTC or ETH to buy Tomo. 

https://medium.com/@eric585696/blockchain-accounts-82f933f0569a

**Comment by etienne-napoleone** [comment]
Thanks @bluebottleco ! I added some comments directly on Medium!
Btw you can add it to the TomoChain publication, we will not publish it until it's ready but all the TomoChain editors can view the draft, view other editors comments and comment

**Comment by etienne-napoleone** [comment]
Thanks @bluebottleco , the article looks good to me now.
Ready for you @alex9121
