### ISSUE TITLE
Write a "get started" for masternode owners

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#109]
**Estimated time:** 20h

---------------

**Why:**
We want to split the get started section by user role. One of them is the masternode owner.

**What:**
Needs to be a comprehensive "tutorial" like introduction to running a masternode.
Should include:
- installing deps (docker, python)
- how to use tmn
- running the node
- checking that he's online (on stats)
- applying as candidate on TomoMaster
   - Connecting your wallet (with TomoWallet)
   - Applying
   - Editing MN information
- Check rewards after one epoch of being elected as masternode
- Anything else if you have some ideas

Alter references to it:
- https://github.com/tomochain/tomochain/edit/master/README.md
- https://medium.com/tomochain/how-to-run-a-tomochain-masternode-from-a-to-z-3793752dc3d1
- 

You can check the difference in writing style between get started "how-to like writing and formal documentation here:
https://docs.docker.com/get-started/#recap-and-cheat-sheet
https://docs.docker.com/engine/reference/builder/

**Comment by nyeates** [comment]
It is in usable state but not complete. Gets user to point of having
started their full node (but not checking status or registering for MN
candidacy etc). I have not yet had chance to work on it this week but now
that all my Masternodes are up finally, I hope to get some time on the
later half of this week.

I am unsure yet how to integrate this page into the docs site. Do we just
put it into the Getting Started Menu items even though they wont match the
existing items?

**Comment by nyeates** [comment]
@phamvancam2104 or @etienne-napoleone where do I find the document that needs to reference this masternode guide? I want to begin to integrate it into the docs menu system etc. Once I learn, I can make other potential organizational changes too... thanks.

**Comment by phamvancam2104** [comment]
@nyeates Can we replace the content of this page https://docs.tomochain.com/masternode/requirements/ with what you are writing?

**Comment by etienne-napoleone** [comment]
As we discussed during the meeting, this is supposed to be part of the reorganization of the "get-started" section if I'm not mistaken

**Comment by nyeates** [comment]
The vision that @etienne-napoleone explained was that the "get started" section becomes oriented at particularly common use-cases and they are more step-by-step guide-like. Whereas the content under those other sections are like technical deep-dives and not as much step-wise.... more matter-of-fact. There would be content overlap.

Some of the content on https://docs.tomochain.com/masternode/requirements/ needs to be updated with what I have created, yes, but I think can remain separate.

**Comment by nyeates** [comment]
> where do I find the document that needs to reference this masternode guide? 

I see the mkdocs.yml which might answer my question....will mess with this tomomorrow.

**Comment by phamvancam2104** [comment]
> > where do I find the document that needs to reference this masternode guide?
> 
> I see the mkdocs.yml which might answer my question....will mess with this tomomorrow.

Yes. It is.

@etienne-napoleone @nyeates I think the getting started page should not be as long as this awesome guide. As an ordinary user, I'd to have a first overview about the masternode and the requirements for it, which should then point to this detailed, step-by-step guide. For me, putting the content of this https://docs.tomochain.com/masternode/requirements/ in Getting started page, and putting this long, detailed guide under Masternode tab would be more natural.

**Comment by etienne-napoleone** [comment]
It's really up to you, but to me the difficulty here is to not mix tutorial, articles, howtos, technical documentation, etc.

How I see it is that the `masternode` section is really the technical documentation like you would do one for an api or so.
For ex. the readme of the `tmn` redirect to https://docs.tomochain.com/masternode/tmn/ .
Where the get started part could be an opinionated how-to with references to the more in depth/technical documentations in the other sections.
This is for example how Docker documentation is structured.

This is just how I saw the organization, if you feel like doing it in another way @phamvancam2104 , just keep in mind that `tmn` in not the only way of running a mn, and you would need to so a similar tutorial on running with docker + another page for the full documentation on both those solutions (or integrate the full doc in the tutorial, but seems a bit heavy)

**Comment by phamvancam2104** [comment]
closed in #112
