### ISSUE TITLE
Add logo for site

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/docs#11]
Add logo tomochain to docs site

**Comment by etienne-napoleone** [comment]
I think it can be closed as thanhson1085@5c45a2a4e3e7d7fe92cc4bd0317011fd7f7042c8

**Comment by etienne-napoleone** [comment]
I think it can be closed as thanhson1085@5c45a2a4e3e7d7fe92cc4bd0317011fd7f7042c8

**Comment by etienne-napoleone** [comment]
I think it can be closed as thanhson1085@5c45a2a4e3e7d7fe92cc4bd0317011fd7f7042c8
