### ISSUE TITLE
Guideline how to build DApps on tomochain 

### ISSUE THREAD

**Issue by phamvancam2104** [tomochain/docs#114]
**Estimated time:** [8]h

---------------

(**Why:**)
We don't have an official document on how to build and deploy a simple Dapps on TomoChain, despite the fact that TomoChain is a blockchain infrastructure for practical decentralized applications.

**What:**
The document could be focusing on how to develop a simple smart contract written in Solidity, and deploy it on TomoChain testnet.

The structure of the document could be similar to that of this article https://medium.com/@nuuneoi/how-to-compile-deploy-and-test-a-smart-contract-on-tomochain-testnet-505eca8c9586 
However, most information in the article is outdated.
Also, because deploying a smart contract on mainnet is much similar to testnet, the differences are just the configuration information, the document should explicitly mention the differences where possible.

**Comment by phamvancam2104** [comment]
Assigned to @DuqueKarl since it seems that you have enough technical background

**Comment by phamvancam2104** [comment]
Assigned to me since @DuqueKarl confirmed that he is not able to solve this issue.

**Comment by phamvancam2104** [comment]
Reassigned to @DuqueKarl since he reconfirmed with me that he can do it

**Comment by DuqueKarl** [comment]
Medium Draft for revision:
https://medium.com/@dkarl/how-to-build-a-dapp-on-tomochain-85532a1192e7

**Comment by phamvancam2104** [comment]
Thanks @DuqueKarl let me have a look!

**Comment by phamvancam2104** [comment]
I added some comments on the article, most of them are minor.

The only major (not really major) change should be using the mobile version TomoWallet instead of web app version to create a wallet.
