### ISSUE TITLE
Writing a tutorial on how to deploy an ICO smart contract on TomoChain

### ISSUE THREAD

**Issue by phamvancam2104** [tomochain/docs#121]
**Estimated time:** [8]h

---------------

(**Why:**)
Some of our partners are confused about doing an ICO smart contract on TomoChain and would like to have a tutorial.

**What:**
Take an ICO smart contract from any ICO project, e.g. TomoChain ICO contract (https://github.com/tomochain/ico-contracts).
The article should explain some important concepts such as TRC-20, total supply, whitelist, ICO rounds, how token balance is transferred between accounts, how to send tokens from an account to another account.

**Comment by phamvancam2104** [comment]
Assigned to @DuqueKarl because he knows how to deploy a smart contract.
Reviewed by @phamvancam2104

**Comment by DuqueKarl** [comment]
Submitted for review:

https://medium.com/p/782142d95538/

**Comment by phamvancam2104** [comment]
thanks @DuqueKarl

**Comment by DuqueKarl** [comment]
Thanks @phamvancam2104 . Updated the article with your comments and suggestions there

**Comment by phamvancam2104** [comment]
Thanks @DuqueKarl I have talked to @alex9121 about publications

**Comment by phamvancam2104** [comment]
Closed by this article https://medium.com/p/782142d95538/
