### ISSUE TITLE
Bring Wallets document over to official docs page

### ISSUE THREAD

**Issue by nyeates** [tomochain/docs#129]
**Estimated time:** 1-3h

---------------

(**Why:**) Having a key document on Google docs looks unprofessional and unpolished. We are slowly trying to get all docs over to docs.tomochain.com.

**What:**
* http://bit.ly/2A6zrC7

Bring this wallet instructions document over to official docs page. Along with all screenshots. It is likely one of the most important pages to new users and voters as the come onboard. Having it be on our central docs website will look more professional and give them more options to view other docs afterwards! Probably it should go inside the `Get Started` section.

**Comment by phamvancam2104** [comment]
We already have this on our docs site (https://docs.tomochain.com/get-started/wallet/)

**Comment by phamvancam2104** [comment]
Closed because it overlaps with this https://docs.tomochain.com/get-started/wallet/
