### ISSUE TITLE
Write a tutorial on how to deploy an NFT tokens on TomoChain

### ISSUE THREAD

**Issue by phamvancam2104** [tomochain/docs#138]
**Estimated time:** [10]h

---------------

(**Why:**)
As more and more applications are willing to use NFT tokens, especially blockchain gaming and enterprise-oriented applications, a tutorial on deploying NFT tokens on TomoChain is definitely necessary.

**What:**
I think the article should mainly explain:

- Differences between a fungible token and a non-fungible token (NFT)
- Show some use-cases of NFT (i.e. ERC721 in cryptokitties)
- Show how-to step by step on deploying an NFT token on TomoChain

Sources for reference:
https://medium.com/crypto-currently/the-anatomy-of-erc721-e9db77abfc24
https://medium.com/coinmonks/building-an-erc721-non-fungible-token-smart-contract-and-using-metamask-to-interact-with-it-via-a-59583f0dd6c1

**Comment by phamvancam2104** [comment]
Assigned to @DuqueKarl as he has accumulated enough experience through his recently written two articles on deploying smart contracts on TomoChain.
Reviewed by @phamvancam2104

**Comment by DuqueKarl** [comment]
Draft ready for publishing:
https://medium.com/p/fe476a68594d/

**Comment by phamvancam2104** [comment]
The article is reviewed and looks good to publish.
