### ISSUE TITLE
Explaining TomoChain's new products: TomoX, TomoDEX, and TomoSwap

### ISSUE THREAD

**Issue by phamvancam2104** [tomochain/docs#142]
**Estimated time:** [5]h

---------------

(**Why:**)
As many people are confused or not quite clear about TomoChain new products including TomoX, TomoDEX, and TomoSwap, a medium article to explain and distinguishing these products should be valuable.

**What:**
Explain clearly and simple terms what are TomoX, TomoDEX, and TomoSwap.
Explain the differences between these products and describe how (if possible) they work together in TomoChain's ecosystem.

Referrences:
- TomoX is the decentralized cryptocurrency exchange protocol integrated directly into the consensus/core layer of TomoChain blockchain. TomoX has a Masternode-Relayer architecture. Please refer to [here](https://docs.google.com/document/d/1BuLe5Ci9yTTL_jCLz5eKoQsDGb6CKAyOy__dht8sQkg/edit?usp=sharing) and [here](https://medium.com/tomochain/understanding-tomox-tomochains-decentralized-exchange-protocol-2cfe540bc94b) for more details.
- TomoDEX is TomoChain's relayer (exchange) that interacts with TomoX
- TomoSwap the first decentralized token swap platform that will focus on both user friendliness to end users and liquidity for future financial applications. TomoSwap will play as the transactional layer to allow assets on TomoChain to be converted seamlessly between end users and other applications. More infos on TomoSwap can be found [here](https://medium.com/tomochain/tomoswap-the-first-decentralised-exchange-platform-on-tomochain-9eaf3d8ca21d).

**Comment by phamvancam2104** [comment]
Assigned to @DuqueKarl.
Reviewed by @phamvancam2104

**Comment by DuqueKarl** [comment]
Draft ready for review and comments

https://medium.com/@dkarl/f5868bfb391

**Comment by phamvancam2104** [comment]
closed as the medium article has been reviewed by me!
