### ISSUE TITLE
tutorial “how to use Ledger Nano S with Mycrypto”

### ISSUE THREAD

**Issue by phamvancam2104** [tomochain/docs#146]
**Estimated time:** [3h]h

---------------

(**Why:**)
Some TOMO holders are not able to use Ledger Nano S with MyCryptp

**What:**
The tutorial should show step-by-step how to connect and use Ledger Nano S with TomoChain. The instructions should include using both Eth App and Tomo App on Ledger Nano S

**Comment by thanhson1085** [comment]
Mycrypto does not support Eth on Ledger, So I close this issue.
