### ISSUE TITLE
Run a node with TomoChain binary

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/docs#158]
**Estimated time:** [8]h

---------------

(**Why:**)
Some partners want to run node from binary to easy to control the parameter

**What:**
1. Clone source code, install Golang, build binary
2. Setup wallets, genesis
3. Run node connect mainnet, stats page

Update this page: https://docs.tomochain.com/masternode/tomonative/

**Comment by ngtuna** [comment]
@thanhnguyennguyen After this, can you also update README page ? it has the same content https://github.com/tomochain/tomochain/blob/master/README.md

**Comment by thanhnguyennguyen** [comment]
Sure
