### ISSUE TITLE
Rework top level of documentation

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#50]
I think it's quite important that we rework the documentation structure.
Our docs.tomochain.com will have documentations for at least five products:
- TomoChain Go client
- TomoMaster
- TomoScan
- TomoWallet
- Masternode related stuff (tmn, images, etc)

In addition to that, there is a lot of research, business related categories like:
- use cases
- whitepapers
- faq
- etc

The current organization doesn't seem good enough to me as the top level is too general
Here is a quick draft of how we could organize it:

```
Introduction

General
 Use cases
 Networks
 Voting
 Important links
 FAQ

TomoChain client
 Getting started
 Contributing

TomoMaster
 Getting started
 Contributing

TomoScan
 Getting started
 Contributing

TomoWallet
 Getting started
 Contributing

Masternode
 Getting started
 Tmn
 Docker
 Contributing
 FAQ

Whitepapers and research
 Technical whitepaper
 Economical whitepaper
 Sharding draft
``` 
The sub categories are examples

Please give me your opinion on this draft

**Comment by thanhson1085** [comment]
Nice re-structure. Where can we add "release notes"  like https://squidfunk.github.io/mkdocs-material/release-notes/?

**Comment by thanhson1085** [comment]
Agree for per-project release notes. (submenu for per-projects)

Where we can add some articles like "how to install MN on DigitalOcean?"
"how to" article should be posted on Medium or the docs site or some where?

**Comment by etienne-napoleone** [comment]
Ok, I will create an issue for that as it's not directly related to the structure but a feature in itself :+1: 

The tutorials, howtos, steps by steps, articles, etc will be posted on medium yes! But the organization/planning will use issues/milestones/projects of this repo
