### ISSUE TITLE
Article on the supposed EOS/Huobi "scandale"

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#53]
**Estimated time:** 5h

---------------

**Why:**
In short, Huobi, famous Chinese exchange, has been accused of abusing the EOS voting system for profit.
Our governance system share certain characteristics as outlined in a previous article written by @phamvancam2104 [TomoChain vs EOS.io](https://medium.com/tomochain/tomochain-vs-eos-io-the-battle-of-posv-vs-dpos-or-just-some-coincidence-of-design-philosophy-b5f606a1e5df).
As people might question themself about potential problems of that sort on TomoChain, this subject could be important to treat.

**How:**
The goal would be to write an article in two parts:

1. What exactly is claimed by the accusers, what is at stake
2. What differences between EOS and Tomo could be beneficiary in that situation

The article should not bring down EOS as we don't even know if those accusation are real. It should stay neutral and present the problem, the stakes and the technical differences between the two projects.

**Related sources:**
- https://cointelegraph.com/news/huobi-on-alleged-eos-mutual-voting-scandal-no-financial-contracts-involved
- https://medium.com/huobi-global/announcement-regarding-the-recent-eos-voting-argument-51a46e4f9458
- https://cointelegraph.com/news/ethereum-vs-eos-shots-fired-on-reddit-as-vitalik-dan-larimer-clash

**Comment by patrickburm** [comment]
https://docs.google.com/document/d/1lVrUr2DszntLa9lpb_I9LbZFMM2M3AC86HJfAh5NOZA/edit?usp=sharing

**Comment by etienne-napoleone** [comment]
@anhntv2012 will take a look at that to make sure it's in line with our editorial line (pretty sensitive subject I guess!)

**Comment by etienne-napoleone** [comment]
After review, even if the article takes a neutral stance, we don't want to go in this direction with the publications.

**Comment by etienne-napoleone** [comment]
After review, even if the article takes a neutral stance, we don't want to go in this direction with the publications.

**Comment by etienne-napoleone** [comment]
After review, even if the article is written with a quite neutral point of view, we decided to not publish because we might not want to take the editorial line this way.

**Comment by etienne-napoleone** [comment]
After review, even if the article is written with a quite neutral point of view, we decided to not publish because we might not want to take the editorial line this way.
