### ISSUE TITLE
Article on how to run a masternode from A to Z

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#54]
**Estimated time:** 5h

---------------

**What:**
Step by step guide on how to run a masternode on Digital Ocean with `tmn`.
From creating a droplet to the node being elected.

**Comment by etienne-napoleone** [comment]
@DuqueKarl You can find the contribution guidelines for the docs repo in the [readme](https://github.com/tomochain/docs#contribution-guideline).
I'm of course available for any question!

**Comment by DuqueKarl** [comment]
@etienne-napoleone Please find below a draft of the article. Let me know if there is anything you would like me to add or change. Thank you!

https://docs.google.com/document/d/17Lg0cD8PyFZIf_0pGpIp7f-bKgkUhm_lC2wijCtL8_4/

**Comment by DuqueKarl** [comment]
@etienne-napoleone 
I have prepared the article for publishing on Medium. Please, find below a draft of the writing. Let me know your suggestions to add or change to improve the article. Thank you!

https://medium.com/p/3793752dc3d1/

**Comment by etienne-napoleone** [comment]
The article content is now ok. @alex9121 you can enhance and publish it when you want
