### ISSUE TITLE
Video on how to run a masternode from A to Z 

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#55]
**Estimated time:** 6h

---------------

**What**:
Step by step guide on how to run a masternode on Digital Ocean with tmn.
From creating a droplet to the node being elected.

**Comment by etienne-napoleone** [comment]
Waiting on new mic

**Comment by phamvancam2104** [comment]
I closed it because there are already enough resource for masternode owners to run a masternode.
