### ISSUE TITLE
 Video on how to vote from A to Z

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#56]
**Estimated time:** 3h

---------------

**What:**
Step by step guide on how to vote on TomoMaster.
From creating a wallet to receiving rewards.

**Comment by etienne-napoleone** [comment]
Waiting on new mic

**Comment by Denni-Lovejoy** [comment]
Hey, I'd like to do the two tutorials needed for Tomochain listed here on Github; "Video on how to vote from A to Z" & "Video on how to run a masternode from A to Z". Who can I speak with regarding answering any technical questions? And who can I speak with regarding submitting a proposal for these two videos?

**Comment by phamvancam2104** [comment]
Thanks @Denni-Lovejoy for your interest in the issue. However, as this video now becomes useless (since voting now is intuitive and no need for a demo video) .I'll then close the issue.
