### ISSUE TITLE
Article explains our slash mechanism on tomochain

### ISSUE THREAD

**Issue by ngtuna** [tomochain/docs#57]
**Estimated time:** 2h

---------------

**Why:** We have injected a simple slashing mechanism into POSV consensus. In general POS, slashing is an important feature to penalize bad staker/masternode who does some bad works which affects to the overall network. All POS competitiors such as Ethereum, EOS, etc they also include slashing in their implementation. We should have one article explaining our slashing.

**What:** I think its structure should be like this: 1) quick introduction about POSV and slashing 2) how tomochain slashing works 3) some comments on that (comparison to other solutions, benefit/drawback)

Some refs: 
https://medium.com/@VitalikButerin/minimal-slashing-conditions-20f0b500fc6c
https://www.reddit.com/r/ethtrader/comments/6qo6pm/vitalik_briefly_explains_why_dpos_tezos_eos_et_al/

**Comment by etienne-napoleone** [comment]
@patrickburm will review the english on this article.
**Estimated time**: 1h30

**Comment by etienne-napoleone** [comment]
Changed english review from @patrickburm to @bluebottleco

**Comment by bluebottleco** [comment]
@phamvancam2104 I really enjoyed reading this article and genuinely learned a lot about slashing from reading it. 

I made some suggestions in terms of grammer/wording on the google doc below. 
https://docs.google.com/document/d/1GIVL21DzorVQKT7WY7FTm3Ef8oc2EZ8oi4sBni5OVAY/edit?usp=sharing

**Comment by phamvancam2104** [comment]
Thank you very much, @bluebottleco, your comments are greatly useful and I really appreciate. I'll incorporate your comments. If you have any other feedback, I'd love to see it.

**Comment by phamvancam2104** [comment]
I've incorporated all comments from @bluebottleco, if anyone of you has some more feedback, please let me know. Thanks

**Comment by etienne-napoleone** [comment]
Looks great to me. I will check with @alex9121 for publishing time.
@phamvancam2104 Can you submit it to the TomoChain publications?

**Comment by phamvancam2104** [comment]
just submitted, please check it @etienne-napoleone

**Comment by etienne-napoleone** [comment]
Thanks @phamvancam2104! Closing this issue. @alex9121 and marketing team will integrate it in their publication schedule.
