### ISSUE TITLE
Article about economic incentive and penalty for participants in the TomoChain ecosystem

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#62]
**Estimated time:** 5h

---------------

**Why:**
An article about this subject would help people understand how the system is using the economic incentive and game theory to ensure the best performance and a stable ecosystem.

**What:**
The article should explain the economical benefits and penalties to the participants in the ecosystem.
Important points:
- block rewards
- token lockup time for both mn and voters
- losing Masternode position
- losing deposits

@anhntv2012 maybe you have some more details to add?

**Comment by anhntv2012** [comment]
Not at the moment, Etienne :D Thanks for asking ^_^

**Comment by bluebottleco** [comment]
@etienne-napoleone Please find below a draft of the article. Let me knows if there is anything you would like me to add or change. Thank you! 
https://medium.com/@eric585696/tomochain-how-a-stable-ecosystem-is-created-8d09717ce755

**Comment by etienne-napoleone** [comment]
Thanks @bluebottleco !
Just read it and it's concise and clear, I like it.
I added a comment on the `Elimination of Weak Masternodes` part, I'll let you check.
Maybe @anhntv2012 has any comment regarding to content?
And @alex9121 regarding to the layout? (ex: image used?)

**Comment by bluebottleco** [comment]
@etienne-napoleone Thank you for the feedback. I made updates to that section per your comments.

**Comment by alex9121** [comment]
Thanks guys. 
When are you going to publish it?

**Comment by anhntv2012** [comment]
Hi @bluebottleco Very nice to meet you.

I would like to have some comments as follows:

1. Lock times:
"Tokens that are staked through voting can be withdrawn to a personal wallet and used to vote for another candidate, but the tokens will be locked for the next 48 hours (86,400 blocks) after they are withdrawn."
The tokens will be locked for the next 48 hours after the unvoting. They can only be withdrawn after that locking period.

2. Weak masternodes
 "when a weak masternode does not get involved in any block within an epoch, the masternode won’t receive any rewards and neither will the stakers of that masternode"
It should be clear that weak masternode is the one who did some block creation/verification but its performance is bad (the number of signatures it made is too low compared to 900, for example), not only those who did nothing.

3. Elimination of weak masternodes
"Masternodes that create a fraudulent block will be detected and penalized by losing all of their deposits to the node that detects the invalidity of the block"
It should be noted that all the masternodes that created/verified the invalid block are penalized., not only the one who created it.

4. Too big too fail
- "The rewards that go to stakers are rewarded proportionally to the number of tokens staked a specific masternode has."
I think that this is not correct. The more tokens voted for a specific masternode, the less reward per token a voter can receive. Or the reward per token is inversely proportional to the number of tokens voted for a specific masternode. 

- I myself would not use the term "too big too fail" in this situation as the theory asserts that "certain corporations, particularly financial institutions, are so large and so interconnected that their failure would be disastrous to the greater economic system, and that they therefore must be supported by government when they face potential failure", which I don't think there is any support by a "government" if the corporation "masternode" faces potential failure.

5. Block reward
"The main economic incentive for running a masternode (50K tokens) or voting for masternodes by staking tokens will be token rewards"
The information given in parentheses is insufficient. To be able to run a masternode, a holder has to not only deposit 50K TOMO but also be in the top 150 most voted candidates. 

That's just my 2 cents @etienne-napoleone 
Let me know how you think.

**Comment by etienne-napoleone** [comment]
@anhntv2012 I agree with those points! Thanks!

Although point 3 has already been updated since you read it. But it needs a new change in my opinion:

@bluebottleco you might have taken my remark too literally, the 50% was an example and it's not fixed.
Let's say a healthy mn during an epoch does 1000 actions (creating blocks, validating blocks, etc.) and receive 1000 TOMO
if it would have done only 645 actions because it was under too heavy load or an incident happened, it would have received only 645 TOMO
(Numbers are just to illustrate)

In another way: 
- rewards are "per action"
- Actions are more or less dispatched equitably between all masternodes due to their mechanisms. Creating new blocks: round robin. double validation: round robin + randomness. etc,)
- Less actions = less rewards
- If the machine is powerfull enough, it will not miss any of it's assigned action and will get the maximum rewards

@alex9121 soon yes, we just need the medium accounts thingies to be ready, can you check that with whom it may concern directly on telegram?

**Comment by bluebottleco** [comment]
I appreciate the feedback and will incorporate the comments now. Thanks!

**Comment by bluebottleco** [comment]
@etienne-napoleone I have finished incorporating all the comments. Please let me know if there is anything else I should change. Thanks! 

Article: https://medium.com/@eric585696/tomochain-how-a-stable-ecosystem-is-created-8d09717ce755

**Comment by etienne-napoleone** [comment]
Thanks @bluebottleco, all the mentioned points look good now. It's all good for me now!
We just need to check with @alex9121 how to add your medium account as writer for the TomoChain publications channel

**Comment by etienne-napoleone** [comment]
@bluebottleco Everything has been validated, thanks! @alex9121 and marketing team will incorporate it in their publication schedule.
