### ISSUE TITLE
Add TomoChain sharding proposal 

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/docs#65]
**Estimated time:** 2h

---------------

**Why:**
- More SEO friendly than Google Docs
- User can read  TomoChain sharding proposal in the docs site

**What:**
TomoChain sharding proposal https://docs.google.com/document/d/1u7TajABjbllZTAkz741wqvbP5v4t4HvJq935rpefvBE/edit

**Comment by etienne-napoleone** [comment]
merged in #68
