### ISSUE TITLE
Add TomoChain economics paper

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/docs#66]
**Estimated time:** 2h

---------------

**Why:**
- More SEO friendly than Google Docs
- User can read TomoChain sharding proposal in the docs site

**What:**
TomoChain economics paper https://docs.google.com/document/d/197Cu57A6OYPoEQbrUVr067qNVEzP_FEwaDCFff7hnlM/edit

**Comment by etienne-napoleone** [comment]
closed in #67
