### ISSUE TITLE
Article on how to vote from A to Z

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#72]
**Estimated time:** 4h

---------------

**Why:**
Follow up to https://github.com/tomochain/docs/issues/54, we also need a A to Z tutorial for voting

**What:**
An article explaining how to vote from A to Z. "A" being creating a wallet and "Z" receiving rewards from your staking.
Should include:
- Creating a wallet
- Connecting the wallet to testnet(metamask) and TomoMaster
- Chosing a Masternode (quick refreshing about how rewards works)
- Voting
- Receiving rewards
- Unvoting
- Withdrawing

**Comment by etienne-napoleone** [comment]
Also please @Leoloup , can you give me your medium handle (create an account if you don't have one already) and we will add you to the TomoChain publications team on medium as writer

**Comment by Leoloup** [comment]
https://medium.com/tomochain/how-to-vote-from-a-to-z-using-tomomaster-2f8948b436a5 Draft link

**Comment by etienne-napoleone** [comment]
Thanks @Leoloup !
I edited the document a lot because we would like to publish this asap (it will help with the hunting game).
For me it's ready now :) Closing this issue.

@alex9121 please read it before publishing, if you see something weird just tell me.

**Comment by alex9121** [comment]
Thanks everyone. 
I will check it again before publishing. 
My plan is to publish it before the game hunter is on so I can attach the guideline for members to follow.
