### ISSUE TITLE
Use Ledger with TomoChain

### ISSUE THREAD

**Issue by thanhson1085** [tomochain/docs#74]
**Estimated time:** 4h

---------------

**Why:**
To guide user use Ledger with TomoChain

**What:**
Suggestion for steps:
- Use Myetherwallet, connect Ledger and TomoChain Testnet
- Use TomoWallet, send 10 TOMO to Ledger address
- Send back from Ledger to TomoWallet
- Check Tx on TomoScan

**Comment by bluebottleco** [comment]
@etienne-napoleone 
Please find below my draft of the article. Let me know if you have any feedback, thanks! 

https://medium.com/@eric585696/using-your-ledger-wallet-with-tomochains-testnet-e8404e8e541e

**Comment by etienne-napoleone** [comment]
Looks all good to me! :+1: 
@bluebottleco Please publish it under the TomoChain channel with "add to publication" and then "ready to publish"
![screenshot from 2018-10-29 10-56-27](https://user-images.githubusercontent.com/26155267/47628684-50e47a80-db69-11e8-85ca-90a41eccc5fd.png)
In general you can use that for our review as this will not publish it directly but allow all editors from the TomoChain channel to review/edit it :)

@alex9121 I'm closing this issue, you can take over this article

**Comment by bluebottleco** [comment]
@etienne-napoleone Okay, just did that with the article. I will do this in the future as well. Thanks!
