### ISSUE TITLE
Announcment about TomoChain JP office

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#83]
**Estimated time:** 2h
**Reviewed by:** @anhntv2012 

---------------

**Why:**
TomoChain is opening an office in Japan and want to communicate about it through medias.

**What:**
A medium announcement article that we can share to our community and to other medias.

**Related ressources:**
- JP office video presentation draft (private)
- [other announcments](https://medium.com/tomochain/english/home)

**Comment by bluebottleco** [comment]
@etienne-napoleone 

I looked at a few other articles about new office openings and they were generally pretty short. I put the draft on google docs for now. Other than general feedback I had a few comments/questions regarding changes to what I wrote before updating it to medium (unless the team would like to post it through their own official medium account)
1. Please let me know if there is better quote from Long Vuong I should use 
2. What email is best to use for contacts about business opportunities. 

https://docs.google.com/document/d/1qjf_Q-m251Cj6oRomP4scTFFnEykCbur4-WoO3CLv-E/edit

**Comment by anhntv2012** [comment]
Thank you @bluebottleco You are quick ^_^
The time for the announcement will be decided later and it will be posted in our official channels as well as several media. I'll add some more information directly to the draft. I'll let you know when it's done so you can edit it for me. 

Thank you
Anh

**Comment by anhntv2012** [comment]
@bluebottleco blu
Please have a look and edit the final draft.
Much appreciated.

**Comment by etienne-napoleone** [comment]
Approved by @anhntv2012 as done
