### ISSUE TITLE
Draft User's privacy/data protection policy and term of services

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/docs#98]
**Estimated time:** 3h

---------------

**Why:**
We need to write ToS and privacy policies for our services (TomoMaster, TomoScan and TomoWallet)

**What:**
Draft ToS and privacy policies for:
- [ ] TomoMaster
- [ ] TomoScan
- [ ] TomoWallet

Also we might want to check GDPR compliance for UE countries.

**Comment by bluebottleco** [comment]
https://drive.google.com/drive/folders/14s8DGgrzrnHBqkvsU2IdoMdKFXA0yi2M?usp=sharing

Tomoscan and TomoWallet were a bit easier to find ToS and privacy policies that I could base one off of, but it was pretty hard finding a ToS and Privacy Policy to build for TomoMaster.

**Comment by etienne-napoleone** [comment]
I'm closing this issue as the current files are enough to be used as a base.
If any more work is required from technical writers, feel free to reopen
